id: P004363
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:15:09.582265
source_metadata:
  id: bdr:W1KG10449
  title: བཟོ་རིག་བསྟན་བཅོས།
  author: ''
  volumes:
    654e106fe21048c6bd92953d6adad535:
      image_group_id: I1KG10451
      title: ''
      volume_number: 1
      total_pages: 278
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
